name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: my-portfolio/package-lock.json

      - name: Install dependencies
        working-directory: my-portfolio
        run: npm install

      - name: Install svelte scrolly
        working-directory: my-portfolio
        run: npm install svelte-scrolly

      - name: Install map dependency
        working-directory: my-portfolio
        run: npm install maplibre-gl

      - name: Generate loc.csv
        working-directory: my-portfolio
        run: npx elocuent -d static,src -o static/loc.csv

      - name: build
        working-directory: my-portfolio
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "my-portfolio/build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4